name: Bug Report
description: Report a bug or issue with PostPilot
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this bug! Please provide the following information.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Web (browser)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: PostPilot version (e.g., 1.0.0)
      placeholder: "1.0.0"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug and how to reproduce it
      placeholder: |
        ## Summary
        A brief description of the issue.

        ## Steps to Reproduce
        1. Go to '...'
        2. Click on '...'
        3. See error

        ## Expected Behavior
        What you expected to happen.

        ## Actual Behavior
        What actually happened.

        ## Additional Context
        Screenshots, error messages, or any other helpful information.
      value: |
        ## Summary


        ## Steps to Reproduce
        1.
        2.
        3.

        ## Expected Behavior


        ## Actual Behavior


        ## Additional Context

    validations:
      required: true
