name: Feature Request
description: Suggest a new feature or improvement for PostPilot
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! We appreciate your input to make PostPilot better.

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of PostPilot would this affect?
      options:
        - API Client
        - Database Client
        - Data Inspector / JSON Viewer
        - Collections & Organization
        - Variables & Environment
        - UI/UX
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see
      placeholder: |
        ## Problem
        What problem would this solve? What are you trying to accomplish?

        ## Proposed Solution
        How would you like this feature to work?

        ## Use Case
        Describe a specific scenario where this would be helpful.

        ## Additional Context
        Screenshots, mockups, or examples from other tools (optional).
      value: |
        ## Problem


        ## Proposed Solution


        ## Use Case


        ## Additional Context

    validations:
      required: true
